### ISSUE TITLE
15.12.0-rc1

### ISSUE THREAD

**Issue by jrha** [quattor/release#236] opened 2015-12-12 17:22 UTC
Top level issue tracker for any blocking issues discovered with 15.12.0-rc1.

**Comment by jrha** [comment] 2015-12-17 13:57
@jouvin have you (or anyone at LAL) had a chance to test this?

**Comment by jouvin** [comment] 2015-12-17 14:02
No not a second!!! Just running from one meeting to another one... May be tomorrow.

**Comment by kwaegema** [comment] 2016-01-05 15:32
We've seen an issue in ncm-lib-blockdevices. we're now checking where it comes from and if it is in the release. Will report asap

**Comment by jrha** [comment] 2016-01-05 16:28
Ok thanks

**Comment by jouvin** [comment] 2016-01-05 16:54
Deployed at LAL on a few machines with different profiles (grid, non grid): no obvious problem seen, deployement successful.

**Comment by kwaegema** [comment] 2016-01-05 16:57
It is in combination with anaconda 7.1: when swap partition is in ks with '--noformat' option , anaconda doesn't write a swap entry to /etc/fstab

**Comment by jrha** [comment] 2016-01-06 13:01
So it's an anaconda bug?

**Comment by jouvin** [comment] 2016-01-06 13:27
I just found that we had our EL7 machines running without a swap because there was no swap entry in fstab. But our machines were installed with 15.4.0. So I'd say that 15.12 doesn't improve anything but doesn't make anything worse. I would not consider it as a showstopper for the release, even though having a fix would be great.

**Comment by jouvin** [comment] 2016-01-06 13:33
In fact, thinking a little bit more to this, I think this is an intentional and good change of behaviour. Previously, a swap partition marked noformat in kickstart was added to fstab with the result that `swapon` will mount your swap and overwrite everything in the partition (as `swapon` doesn't make any check about the partition type or existing contents). In this sense, not adding a swap partition not formatted by Kickstart to `fstab` seems to me a consistent behaviour. Probably we should update our configs so that a swap partition declared in a profile is not marked `noformat` and document this required change in configs when moving to EL7.

**Comment by stdweird** [comment] 2016-01-06 13:54
in EL7, swapon/swapoff is not the issue. systemd will scan fstab, and generate a unit for each partition/filesystem/swap/.... if the entry is not present in fstab, there's no easy way to enable swap.
the problem is that we create swap in `%pre` in kickstart, so we do format the partition in pre, and than `--noformat` in the kickstart section does make sense. so this is somewhat similar to the mandatory reformatting of `/` that was already present in el70.
(not adding existing swap partition in fstab is some container/vm feature apparently).

but strictly speaking this is not a 15.12 issue (i asked @kwaegema to open an issue here because my initial interpretation of the missing swap was some bug that crept in the libblockdevices code).

**Comment by kwaegema** [comment] 2016-01-06 13:58
indeed, not specific for .12 , it is just the new anaconda version. PR that makes swap show up in fstab is here : https://github.com/quattor/aii/pull/155

**Comment by jrha** [comment] 2016-01-07 11:28
Building RC2 now.

**Closed** 2016-01-07 11:28 UTC
Labels: tracker
