### ISSUE TITLE
unable to create rpm dependencies

### ISSUE THREAD

**Issue by stdweird** [quattor/release#83] opened 2015-04-02 12:57 UTC
making rpm dependencies like

```
Requires: ncm-metaconfig >= 15.2
```

is impossible, because our metadata is completely messed up, e.g.

```
# repoquery --whatprovides 'ccm >= 100.0.0'
ccm-0:14.8.0-1.noarch
ccm-0:14.5.0-rc2_1.noarch
ccm-0:14.4.0-rc1_1.noarch
ccm-0:14.6.0-1.noarch
ccm-0:14.8.0-rc3_1.noarch
ccm-0:14.4.0-rc2_1.noarch
ccm-0:13.9.0-1.noarch
ccm-0:14.5.0-1.noarch
ccm-0:14.10.0-1.noarch
ccm-0:14.6.0-rc2_1.noarch
ccm-0:13.5.0-1.noarch
ccm-0:13.3.0-1.noarch
ccm-0:14.5.0-rc1_1.noarch
ccm-0:13.2.0-1.noarch
```

bug needs to fixed (`rpm -q --provides` reports the package names followed with 2 spaces as part of the provides, i assume this is seen as some version wildcard.)

we also need some plan how to set dependencies, since all current rpms allow all future ones.

**Comment by jouvin** [comment] 2015-04-02 13:37
Interesting...

**Comment by jrha** [comment] 2015-04-30 13:49
The trailing spaces are a bug in RPM, see https://bugzilla.redhat.com/show_bug.cgi?id=717534

**Comment by jrha** [comment] 2015-04-30 13:52
Which is confirmed by the repository metadata looking correct.
```xml
<rpm:provides>
    <rpm:entry name="ncm-metaconfig"/>
    <rpm:entry name="ncm-metaconfig" flags="EQ" epoch="0" ver="15.2.0" rel="1"/>
    <rpm:entry name="perl(NCM::Component::metaconfig)"/>
</rpm:provides>
```

**Comment by stdweird** [comment] 2015-05-03 14:13
yes, that might be the culprit. (it also shouldn't provide the 3rd one without version)

**Comment by jrha** [comment] 2015-05-07 11:30
Need to figure out what the maven plugin is doing here.

**Comment by jrha** [comment] 2015-05-13 14:06
Ok, this might be `autoreq`, I've just looked at the `.spec` file generated for `ncm-metaconfig` during the build of 15.4.0-rc2:

```
Name: ncm-metaconfig
Version: 15.4.0
Release: rc2_SNAPSHOT20150513095311
Summary: ncm-metaconfig
License: http://www.opensource.org/licenses/apache2.0
Vendor: Quattor
URL: http://quattor.org/cfg-modules/metaconfig/
Group: Quattor
Packager: Quattor
Provides: ncm-metaconfig
Requires: ncm-ncd
Requires: libuser
autoprov: yes
autoreq: yes
```

**Comment by jrha** [comment] 2015-05-13 14:11
Yup...

```
# find src/configuration-modules-core/ncm-metaconfig/src/ -type f -name \*.pm | /usr/lib/rpm/find-requires
perl(base)
perl(CAF::Service)
perl(EDG::WP4::CCM::Element)
perl(EDG::WP4::CCM::TextRender)
perl(LC::Exception)
perl(NCM::Component)
perl(Readonly)
perl(strict)
perl(warnings)
```

**Comment by jrha** [comment] 2015-05-13 14:46
Adding this:
```perl
use CAF::Service ${rpm.version};
```
Results in this:
```
perl(CAF::Service) >= 15.4.0
```
But also requires us to add something like:
```perl
use version; our $VERSION = version->declare("${rpm.version}");
```
To all of our modules.

See: http://modernperlbooks.com/mt/2009/07/version-confusion.html

**Comment by stdweird** [comment] 2015-05-13 16:04
we could make a maven variable for that, e.g. 
```perl
package NCD::ComponentProxyList;
${perl-header}
```

with `${perl-header}` 
```perl
use strict;
use warnings;
use version;
our $VERSION = version->declare("${rpm.version}");
```
(i don't know if maven will recurisvely replace `${rpm.version}` though)

**Comment by jrha** [comment] 2016-02-12 11:54
Since quattor/maven-tools#62 was merged, the provides are looking good.
```
$ rpm -qp --provides ncm-accounts-15.12.0-1.noarch.rpm
ncm-accounts
perl(NCM::Component::accoun
```

Now we need to tackle the requires.

**Comment by ned21** [comment] 2017-10-26 11:10
@stdweird Has this been fixed by the PMpre and PMpost stuff?

**Comment by stdweird** [comment] 2017-10-26 11:19
yes, switching to that will fix it. it is done for all framework except LC; and gradually being done for the components

**Closed** 2017-10-26 11:21 UTC
